# Generated by Django 5.1.2 on 2024-11-01 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text TG')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time of receipt')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.profile', verbose_name='TG Profile')),
            ],
            options={
                'verbose_name': 'TG Mesasge',
                'verbose_name_plural': 'TG Mesasges',
            },
        ),
    ]
