# Generated by Django 5.1.2 on 2024-11-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_rent_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='aerodrom',
            field=models.CharField(default='Default Aerodrome', max_length=255),
        ),
    ]
