# Generated by Django 5.1.2 on 2024-11-05 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_rent_aerodrom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aerodrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameAerodrom', models.CharField(max_length=255)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Аэродром',
            },
        ),
        migrations.AlterField(
            model_name='rent',
            name='aerodrom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.aerodrom'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
