# Generated by Django 5.1.2 on 2024-11-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_aerodrom_alter_rent_aerodrom_delete_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='aerodrom',
        ),
        migrations.AddField(
            model_name='rent',
            name='dateEnd',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='rent',
            name='dateStart',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='rent',
            name='timeEnd',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='rent',
            name='timeStart',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='rent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания записи'),
        ),
    ]
