# Generated by Django 5.1.2 on 2024-11-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_remove_rent_aerodrom_rent_dateend_rent_datestart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='type_plane',
            field=models.CharField(default='TEST', max_length=255),
        ),
    ]
