# Generated by Django 5.1.2 on 2024-11-07 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_alter_rent_dateend_alter_rent_datestart_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rent',
            options={'verbose_name': 'Бронь самолета', 'verbose_name_plural': 'Бронь самолётов'},
        ),
    ]
