# Generated by Django 5.1.2 on 2024-11-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_alter_rent_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_plane', models.CharField(default='Plane 1', max_length=255)),
            ],
            options={
                'verbose_name': 'Самолёт',
                'verbose_name_plural': 'Самолёты',
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль в телеграме', 'verbose_name_plural': 'Профили в телеграме'},
        ),
    ]
