# Generated by Django 5.1.2 on 2024-11-08 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_planes_delete_plane'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planes',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступен'),
        ),
        migrations.AlterField(
            model_name='planes',
            name='type_plane',
            field=models.CharField(default='Plane 1', max_length=255, verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='Register_flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refueling', models.CharField(max_length=100, verbose_name='Заправка (литры)')),
                ('hobbs', models.CharField(max_length=150, verbose_name='HOBBS')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.profile', verbose_name='Профиль')),
                ('type_plane', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.planes', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Регистрация полёта',
                'verbose_name_plural': 'Регистрация полётов',
            },
        ),
    ]
