# Generated by Django 5.1.2 on 2024-11-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_alter_planes_available_alter_planes_type_plane_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_flight',
            name='hobbs',
        ),
        migrations.AddField(
            model_name='register_flight',
            name='aerodrom_end',
            field=models.CharField(default=None, max_length=200, verbose_name='Посадка где'),
        ),
        migrations.AddField(
            model_name='register_flight',
            name='aerodrom_start',
            field=models.CharField(default=None, max_length=200, verbose_name='Взлёт от куда'),
        ),
        migrations.AddField(
            model_name='register_flight',
            name='commentary',
            field=models.CharField(default='Нет', max_length=300, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='register_flight',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='register_flight',
            name='hobbs_end',
            field=models.CharField(default=None, max_length=150, verbose_name='HOBBS конечный'),
        ),
        migrations.AddField(
            model_name='register_flight',
            name='hobbs_start',
            field=models.CharField(default=None, max_length=150, verbose_name='HOBBS начальный'),
        ),
        migrations.AddField(
            model_name='register_flight',
            name='number_of_landings',
            field=models.PositiveSmallIntegerField(default=None, verbose_name='Количество посадок'),
        ),
        migrations.AddField(
            model_name='register_flight',
            name='time',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='register_flight',
            name='refueling',
            field=models.CharField(default=None, max_length=100, verbose_name='Заправка (литры)'),
        ),
    ]
